/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package ti.jitsi;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiApplication;
import org.jitsi.meet.sdk.JitsiMeetActivity;
import org.jitsi.meet.sdk.JitsiMeetConferenceOptions;

import java.net.MalformedURLException;
import java.net.URL;


@Kroll.module(name = "TiJitsi", id = "ti.jitsi")
public class TiJitsiModule extends KrollModule {

    private static final String LCAT = "TiJitsiModule";
    private static final boolean DBG = TiConfig.LOGD;

    public TiJitsiModule() {
        super();
    }

    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app) {
    }

    @Kroll.method
    public void startConference(KrollDict data) {
        try {

            String server = "https://meet.jit.si";
            String room = "";
            if (data.containsKey("server")) {
                server = data.getString("server");
            }
            if (data.containsKey("room")) {
                room = data.getString("room");
            }

            if (room != "") {
                JitsiMeetConferenceOptions options = new JitsiMeetConferenceOptions.Builder()
                        .setServerURL(new URL(server))
                        .setRoom(room)
                        .setAudioMuted(false)
                        .setVideoMuted(false)
                        .setAudioOnly(false)
                        .setFeatureFlag("toolbox.enabled", false)
                        .setFeatureFlag("filmstrip.enabled", false)
                        .setFeatureFlag("welcomepage.enabled", false)
                        .setFeatureFlag("add-people.enabled", false)
                        .setFeatureFlag("chat.enabled", false)
                        .setFeatureFlag("invite.enabled", false)
                        .setFeatureFlag("prejoinpage.enabled", false)
                        .setConfigOverride("requireDisplayName", false)
                        .build();
                JitsiMeetActivity.launch(TiApplication.getAppCurrentActivity(), options);
            } else {
                Log.e(LCAT, "Room is empty. Please set a room property");
            }
        } catch (MalformedURLException e) {

        }
    }
}
